soc: rockchip: grf: Explicitly include bitfield.h
drivers/soc/rockchip/grf.c:76:14: error: implicit declaration of function 'FIELD_GET' [-Werror=implicit-function-declaration]

Fixes: aa65b81218e7 ("Merge commit '62646c7ab19511b8fc17078cf4b0603e550e73cd'")
Change-Id: I44c101a111911d888774390e7096979971f8c332
Signed-off-by: Tao Huang <huangtao@rock-chips.com>