Revert "mm/sparse: fix BUILD_BUG_ON check for section map alignment"
This reverts commit 28208ad9dae4d1eccc9280bc3193b4091afd6a1a.

sparc64 defconfig:

In file included from <command-line>:
In function ‘sparse_init_one_section’,
    inlined from ‘sparse_init_early_section’ at /tmp/next/build/mm/sparse.c:323:2:
/tmp/next/build/include/linux/compiler_types.h:699:45: error: call to ‘__compiletime_assert_420’ declared with attribute error: BUILD_BUG_ON failed: SECTION_MAP_LAST_BIT > min(PFN_SECTION_SHIFT + __ffs(sizeof(struct page)), PAGE_SHIFT)
  699 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |                                             ^
/tmp/next/build/include/linux/compiler_types.h:680:25: note: in definition of macro ‘__compiletime_assert’
  680 |                         prefix ## suffix();                             \
      |                         ^~~~~~
/tmp/next/build/include/linux/compiler_types.h:699:9: note: in expansion of macro ‘_compiletime_assert’
  699 |         _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
      |         ^~~~~~~~~~~~~~~~~~~
/tmp/next/build/include/linux/build_bug.h:40:37: note: in expansion of macro ‘compiletime_assert’
   40 | #define BUILD_BUG_ON_MSG(cond, msg) compiletime_assert(!(cond), msg)
      |                                     ^~~~~~~~~~~~~~~~~~
/tmp/next/build/include/linux/build_bug.h:51:9: note: in expansion of macro ‘BUILD_BUG_ON_MSG’
   51 |         BUILD_BUG_ON_MSG(condition, "BUILD_BUG_ON failed: " #condition)
      |         ^~~~~~~~~~~~~~~~
/tmp/next/build/mm/internal.h:975:9: note: in expansion of macro ‘BUILD_BUG_ON’
  975 |         BUILD_BUG_ON(SECTION_MAP_LAST_BIT > min(PFN_SECTION_SHIFT + __ffs(sizeof(struct page)),
      |         ^~~~~~~~~~~~

Signed-off-by: Mark Brown <broonie@kernel.org>